### PR TITLE
(#1497) Re-wire how we do NCIDS Js init

### LINKED ISSUE #1497: NciDsJsInit component outputs escaped html instead of script when publishing to doc site.
Using the Header component page as an example of this not working correctly, but:
```
<NciDsJsInit>{`
const elements = preview.querySelectorAll('.nci-header');
elements.forEach((element) => {
	switch (element.id) {
		case 'default-header-example':
			window.ncids.NCIExtendedHeaderWithMegaMenu.create(element, {
				megaMenuSource: new window.ncids.DefaultMegaMenuSource(),
				mobileMenuSource: new window.ncids.DefaultMobileMenuSource(),
			});
			break;
		case 'header-with-mega-menu-example':
			window.ncids.NCIExtendedHeaderWithMegaMenu.create(element, {
				megaMenuSource: window.adapter,
				mobileMenuSource: new window.ncids.DefaultMobileMenuSource(),
			});
			break;
	}
});
`}</NciDsJsInit>
```

Is being generated as:
```
<div>
   const elements = preview.querySelectorAll(&#x27;.nci-header&#x27;);
   elements.forEach((element) =&gt; {
   switch (element.id) {
   case &#x27;default-header-example&#x27;:
   window.ncids.NCIExtendedHeaderWithMegaMenu.create(element, {
   megaMenuSource: new window.ncids.DefaultMegaMenuSource(),
   mobileMenuSource: new window.ncids.DefaultMobileMenuSource(),
   });
   break;
   case &#x27;header-with-mega-menu-example&#x27;:
   window.ncids.NCIExtendedHeaderWithMegaMenu.create(element, {
   megaMenuSource: window.adapter,
   mobileMenuSource: new window.ncids.DefaultMobileMenuSource(),
   });
   break;
   }
   });
   </div>
```

It should be:
```
<script>
const elements = preview.querySelectorAll('.nci-header');
elements.forEach((element) => {
	switch (element.id) {
		case 'default-header-example':
			window.ncids.NCIExtendedHeaderWithMegaMenu.create(element, {
				megaMenuSource: new window.ncids.DefaultMegaMenuSource(),
				mobileMenuSource: new window.ncids.DefaultMobileMenuSource(),
			});
			break;
		case 'header-with-mega-menu-example':
			window.ncids.NCIExtendedHeaderWithMegaMenu.create(element, {
				megaMenuSource: window.adapter,
				mobileMenuSource: new window.ncids.DefaultMobileMenuSource(),
			});
			break;
	}
});
</script>
```

### PR DESCRIPTION
**Pull request by bryanpizzillo**
So TL;DR; Gatsby v3 does not make a static HTML site. It makes some sort of Static/React mess. Add pre-fetching on top of this and we start running into issues with components that need to get added to the DOM happening randomly. This hopefully resolves some of our current issues.

See https://github.com/NCIOCPL/ncids/wiki/Technical:-NCIDS-Initialization-in-Gatsby

Closes #1497

.

### CODE REVIEW

File: docs/src/components/NciDsJsInit.jsx [hunk 1]
```diff
@@ -1,23 +1,20 @@
...
+ * and MDX page.
+ *
+ * @see https://github.com/NCIOCPL/ncids/wiki/Technical:-NCIDS-Initialization-in-Gatsby
+ */
 const NciDsJsInit = ({ path, children }) => {
 	const html = `
 		window.ncidsPreviewHandlers = window.ncidsPreviewHandlers || {};
 	  if (!window.ncidsPreviewHandlers['${path}']) {
-			const handler = (preview) => {
+			console.log(\`Register handler for ${path} \`);
```
Comment (olitharp-nci) [inline docs/src/components/NciDsJsInit.jsx:16]: remove log

**Review by olitharp-nci — CHANGES_REQUESTED** [review]

**Review by olitharp-nci — APPROVED** [review]
