### PR TITLE
(#17) setup ncids-react subrepo;

### LINKED ISSUE #17: Enabler: Setup ncids-react Sub-Repo
# Setup ncids-react Sub-Repo

This is the implementation for React components. The npm package will be published to the NCIOCPL organization's GitHub registry. Any site/application built using these components must also include ncids-css. The storybook output will be published to a subdirectly under the designsystem.cancer.gov site.

Things to do:

For the most part this should follow our React development standards as "defined" in https://github.com/NCIOCPL/cgov-react-app-playground. NOTE: this package is a library, so it will not need most of the dependencies that are used to make an app. (e.g. Axios, Nock, React Fetching, React Helmet, React Tracking, React Router, etc)

* [x] Configure eslint rules
* [x] Configure built scripts (rollup)
* [x] Configure watch
* [x] Setup Jest & React Testing Library for unit tests
* [x] Configure anything else I missed that we would have in a React Library repo.

Things NOT to include:
* [ ] Configure visual regression tests - to be added later.
* [ ] Other Github Actions to publish the package automatically
* [ ] Configure Github Actions to build, lint and test on pull requests - i.e. fail a PR if the code is bad.
* [ ] Configure storybook
   * [ ] Setup Cypress for behavioral tests (Maybe ok with unit tests)
       * Maybe this tests the storybook instead of some index.html with a bunch of components?
* [ ] Example projects

> **ESTIMATE** 3 story points

### Resources:
* https://github.com/NCIOCPL/ncids/wiki/Repos-Packages-Organization#ncids-react

### Prerequisites
- Enabler: Setup Design System Mono Repo #6 

### Notes
* So as noted on the ticket, each component may live in its own package. This way you do not need to worry about

### PR DESCRIPTION
**Pull request by arcepaul**
Closes #17 .

added react and webpack for component development
- task: add rollup build and watch commands
- task: add eslint and linting scripts
- task: implement unit testing; add jest and rtl

### CODE REVIEW

File: packages/ncids-react/lib/index.js [hunk 1]
```diff
@@ -0,0 +1,1379 @@
+'use strict';
```
Comment (bryanpizzillo) [inline packages/ncids-react/lib/index.js:1]: What is this and should it really be comitted here?

**Review by bryanpizzillo — COMMENTED** [review]
I have a question about lib...

**Review by karlikpj — APPROVED** [review]

File: packages/ncids-react/lib/index.js (hunk 1 above)
Comment (arcepaul) [reply packages/ncids-react/lib/index.js]: ok, lib is now untracked and it should be published via github action
