### PR TITLE
(#349) Allow mulitple closable site alert components

### LINKED ISSUE #349: NCISiteAlert only allows for one closable site alert
SP: 3

### Issue description

The site alert is only allowing for one site alert to be dismissible at a time. Update to allow an infinite amount of closable site alerts.

> **ESTIMATE** TBD

### Related Tickets
* #262 
* #350

### LINKED ISSUE #386: Update NCIDS component option type aliases.
> **ESTIMATE** TBD

### Issue description
Component options need to be optional when used in the `create` method, but options should never be undefined in the component.

Required properties:
```ts
/** NCISiteAlert component options. */
export type NCISiteAlertOptions = {
    /** Add close button to component. */
    closeable: boolean;
    /** Site alert close button options. */
    closeButton: SiteAlertCloseButtonOptions;
    /** Site alert collapse options. */
    collapse: SiteAlertCollapseOptions;
};
```

Not defining all properties will throw an error:
```ts
NCISiteAlert.create(<HTMLElement>element, {
    closeable: true,
    closeButton: { ariaLabel: 'test' },
});
```

Dev note: Look into [`Partial<Type>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype)

### PR DESCRIPTION
**Pull request by olitharp-nci**
Closes #349
Closes #386

### CODE REVIEW

File: packages/ncids-js/src/components/usa-site-alert/utils/site-alert-close-button.component.ts [hunk 1]
```diff
@@ -74,16 +47,13 @@ export class NCICloseButton {
 		this.removeEventListeners();
 
 		// Unset cookie
-		document.cookie = `NCISiteAlert=; Path=${this.options.cookiePath}; Expires=Thu, 01 Jan 1970 00:00:01 GMT`;
+		document.cookie = `NCISiteAlert${this.element.id}=; Path=${this.options.cookiePath}; Expires=Thu, 01 Jan 1970 00:00:01 GMT`;
```
Comment (bryanpizzillo) [inline packages/ncids-js/src/components/usa-site-alert/utils/site-alert-close-button.component.ts:50]: Is the requirement a session cookie or a persistent? IIRC, adding a date to a cookie turns it into a persistent cookie. Additionally, on unset, I don't think we should clear out the cookie? (Since it is meant to persist across pages and such...)

Comment (bryanpizzillo) [reply packages/ncids-js/src/components/usa-site-alert/utils/site-alert-close-button.component.ts:50]: Actually, yeah, removing the component should not remove the cookie.

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]
Some items for now pls -- gotta run out.

File: packages/ncids-js/src/components/usa-site-alert/nci-site-alert-options.ts [hunk 2]
```diff
@@ -17,16 +17,16 @@ export type NCISiteAlertOptions = {
  * Allows close button to be optional for user input, but required in the
  * component.
  */
-type NCISiteAlertCloseButtonOptions = Partial<NCICloseButtonOptions> & {
+type NCISiteAlertCloseButtonOptions = Partial<SiteAlertCloseButtonOptions> & {
```
[the remark this answers is not in the document]
Comment (olitharp-nci) [reply packages/ncids-js/src/components/usa-site-alert/nci-site-alert-options.ts:20]: still looking into this - pushing other updates

**Review by blilianyu — APPROVED** [review]
Looks good!

**Review by karlikpj — APPROVED** [review]

**Review by bryanpizzillo — APPROVED** [review]
Everything I was asking for has been updated. It does look like there is a missing test for subscribe and checking if the event was correctly dispatched. I am just tracking this as a bug for now. (#396)

**Comment by bryanpizzillo** [comment]
@arcepaul Can you please put eyes on this tomorrow morning and pull it in if you are all good with it?

**Review by arcepaul — APPROVED** [review]
