### PR TITLE
(#659) Adds Resize Event Listener to Close Mobile Menu

### LINKED ISSUE #659: NCI Header mobile menu should collapse when the page is resized
### Issue description
NCI Header mobile menu should collapse when the page is ~resized~ not supposed to be using a mobile menu
> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Be on mobile
2. Open mobile menu
3.  Resize to tablet or desktop

### What's the expected result?
- Mobile menu hides

### What's the actual result?
- Mobile menu statys open

### Additional details / screenshot
Screen Shot 2022-11-15 at 10 41 32 AM

### PR DESCRIPTION
**Pull request by dlescarbeau**
- Closes #659

### CODE REVIEW

File: packages/ncids-js/src/components/nci-header/utils/mobile-menu/mobile-menu.ts [hunk 1]
```diff
@@ -47,6 +47,9 @@ export class MobileMenu {
 		'nci-is-loading',
 		'hidden',
 	]);
+	/** Desktop Media Query for Closing Mobile Menu */
+	private resizeMediaQuery: MediaQueryList;
+	protected resizeWidth: number | number = 1024;
```
Comment (olitharp-nci) [inline packages/ncids-js/src/components/nci-header/utils/mobile-menu/mobile-menu.ts:52]: number or number?

File: packages/ncids-js/src/components/nci-header/utils/mobile-menu/mobile-menu.ts [hunk 2]
```diff
@@ -76,6 +79,12 @@ export class MobileMenu {
 	 */
 	private menuOpenEventListener: EventListener = (e) => this.handleOpenMenu(e);
 
+	private windowResizeEventListener: EventListener = (query: Event) => {
```
Comment (olitharp-nci) [inline packages/ncids-js/src/components/nci-header/utils/mobile-menu/mobile-menu.ts:82]: can you add doc block

**Review by olitharp-nci — CHANGES_REQUESTED** [review]
small clean up, otherwise looks good
oh plus rebase develop

File: packages/ncids-js/src/components/nci-header/utils/mobile-menu/mobile-menu.ts (hunk 1 above)
Comment (olitharp-nci) [reply packages/ncids-js/src/components/nci-header/utils/mobile-menu/mobile-menu.ts:52]: oh and needs comment block here as well

**Review by olitharp-nci — APPROVED** [review]
