### PR TITLE
(#558) Mobile Search Modal "Rework" | Baby's First PR

### LINKED ISSUE #558: Bug: Menu button and search box shouldn't wrap at smaller screensizes
### Issue description
Starting at screen sizes 409px and below the mobile menu button and the search box wrap to different lines in the header. They should always bee on the same line and the text box of the search box should get smaller.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Reduce screen size to 409 or less
2. Screenshot below of what you'll see:
Header wrapping

### What's the expected result?
- When a user is looking at the header at a screen size of 409px or less the mobile menu button and the search box should be on the same line.
- Screenshot of what is expected below:
Header Mock Up

### What's the actual result?
- See screenshot in steps to reproduce

### Related Tickets
* #3268

### LINKED ISSUE #588: Header Logo Not Left-Aligned on Safari Browser
### Issue description
On Safari browser, the header logo is not left-aligned as it should be on desktop, and is center-aligned on tablet and mobile

> **ESTIMATE** 1

### Steps to reproduce the issue
1. Go to example site on Safari
2. Observe the logo out of place.
3. 

### What's the expected result?
- Header logo should be appropriately left-aligned for all breakpoints

### What's the actual result?
- Header has space on its left side on desktop, and is centered on mobile/tablet.

### Additional details / screenshot
Screen Shot 2022-09-20 at 1 51 47 PM
Screen Shot 2022-09-20 at 1 51 54 PM

### Related Tickets
* Issue #558

### LINKED ISSUE #589: Icons Not Appearing on Safari or iOS
### Issue description
Search Icon, Print Icon, and Mail (Envelope) Icon are not displayed on Safari or iOS (iPhone).

> **ESTIMATE** 1

### Steps to reproduce the issue

1. View the example site in Safari
2. Observe that Print / Envelope icons are missing
2 (Optional). While on Safari, shrink the window until the searchbox wraps under the logo. Observe that the search icon is missing from the search button.

### What's the expected result?
- The Search Icon should be present in the search button at tablet/mobile sizes on all browsers.
- The Print/Mail icon should be present on all browsers.

### What's the actual result?
- All icons described do not display on Safari at any breakpoint.

### Additional details / screenshot
Screen Shot 2022-09-20 at 1 59 55 PM

### Related Tickets
* Issue #558
* Issue #588

### PR DESCRIPTION
**Pull request by dlescarbeau**
Closes #558 
Closes #588 
Closes #589 

- Searchbar / Menu button no longer wrap at small screensizes
- Search expands / Menu button disappears on search focus (mobile only)
- (588) Header logo behaves appropriately on Safari
- (589) Icons now display appropriately on Safari

### CODE REVIEW

**Comment by bennettcc** [comment]
Per standup on 9/22, this has passed product and design review. Awaiting tech review before we consider this ready for merging

**Review by sarinapadilla — APPROVED** [review]
Per standup on 9/22, this has passed product and design review!

**Review by arcepaul — APPROVED** [review]

File: packages/ncids-js/src/components/nci-header/utils/search.ts [hunk 1]
```diff
@@ -99,126 +76,24 @@ export class Search {
...
 	private handleSearch(event: Event): void {
 		event.preventDefault();
-		if (!this.mobileActive) {
-			this.createOverlay();
-			this.mobileActive = true;
-		}
+		const searchContainer = <HTMLElement>(
+			document.querySelector('.nci-header-nav__secondary')
+		);
+		searchContainer?.classList?.add('search-focused');
```
Comment (olitharp-nci) [inline packages/ncids-js/src/components/nci-header/utils/search.ts:82]: Missing code coverage for lines 82-97. 

I assume it's due to the optional chaining on lines 82 and 97. 

We _do_ need to change the code to fail better when search is missing (as currently the component breaks other js from running on the platform if search is missing) - but we'll need 85% branch coverage for this file to pass the PR. Line 82 does not require the optional chaining because of the type casting done on line 79

something like this is the quick fix
```typescript
		const searchContainer = <HTMLElement>(
			document.querySelector('.nci-header-nav__secondary')
		);
		searchContainer.classList.add('search-focused');
   ...
		searchContainer.classList.remove('search-focused');
```

the long fix is to fix the broken search code if the search is not found then add unit tests for a header without a search - but we can definitely add a bug tix for that

Comment (olitharp-nci) [reply packages/ncids-js/src/components/nci-header/utils/search.ts:82]: oh, i noticed that the constructor sets `this.search` with the same selector. If we can, it is better to only query the document once instead of 3 times. is there a need to query it on every user interaction?

File: packages/ncids-js/src/components/nci-header/__tests__/search/search.test.ts [hunk 2]
```diff
@@ -137,7 +68,7 @@ describe('NCI Search', () => {
 
 		fireEvent.focus(inputArea);
 
-		expect(addEventListener.mock.calls).toHaveLength(3);
+		expect(addEventListener.mock.calls).toHaveLength(2);
 		userEvent.keyboard('cancer');
```
Comment (olitharp-nci) [inline packages/ncids-js/src/components/nci-header/__tests__/search/search.test.ts:72]: i know you didn't touch this, but is line 72-75 working? `userEvent` and `waitFor` are missing `await` on the async function calls

File: testing/ncids-css-testing/stories/components/nci-header/nci-extended-desktop-search.stories.jsx [hunk 3]
```diff
@@ -11,13 +11,18 @@ const html = `
 		<div class="nci-header__navbar">
 			${nciImgLogo}
 			<div class="nci-header-nav__secondary">
+				<button class="usa-button nci-header-mobilenav__open-btn">Menu</button>
 				<form action="#" aria-label="Sitewide" class="nci-header-search" method="get" role="search">
 					<label class="usa-sr-only" for="nci-header-search__field">
 						Search
 					</label>
 					<input class="usa-input" id="nci-header-search__field" type="search" name="search" style="border-right:1px solid #1b1b1b;">
-					<div class="nci-header-search__overlay"></div>
```
Comment (olitharp-nci) [inline testing/ncids-css-testing/stories/components/nci-header/nci-extended-desktop-search.stories.jsx:19]: can you confirm that all stories, the documentation site, and the example site are all using the same and correct HTML for search?

**Review by olitharp-nci — CHANGES_REQUESTED** [review]

File: packages/ncids-js/src/components/nci-header/utils/search.ts (hunk 1 above)
Comment (dlescarbeau) [reply packages/ncids-js/src/components/nci-header/utils/search.ts:82]: I had no idea the optional chaining was messing with the tests, I guess that makes sense though. I've removed the optional chaining for now

**Review by olitharp-nci — APPROVED** [review]
