### PR TITLE
(#2076) Modal Tab Focus Error

### LINKED ISSUE #2076: Modal Tab Focus incorrectly functioning
### Issue description
Modal is not grabbing the correct clickable items and need to move the check for focusable items in the 

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  make modal 
2. update content with clickable element
3. tabbing doesnt find new items.

### What's the expected result?
- tabbing should click though all focusable items

### What's the actual result?
-tabbing is not clicking though all focusable items

### Additional details / screenshot
- Screenshot

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by karlikpj**
## Pull Request Details

_Add description_

Closes #2076

## Author PR Checklist
Items that the author of the PR is responsible for checking before submitted the PR.

### General:
- [ ] I have reviewed the acceptance criteria defined in the ticket and ensured the work has been completed.
- [ ] The commit message passes [all quality commit message standards](https://github.com/NCIOCPL/ncids/wiki/Creating-Quality-Commit-Messages).
- [ ] Unit tests have been updated or created to reflect any javascript changes.
- [ ] Storybook scenarios have been updated or created to reflect any html/css/js changes.

### Accessibility:
- [ ] WCAG 2.1 Level AA requirements have been met.

### Development:
- [ ] Any new or updated javascript code has 100% unit test coverage.
- [ ] New or updated breakpoints have regression images.
- [ ] Breaking changes have been thoroughly documented in the PR.

## Product Reviewer PR Checklist
Items the product team is responsible for reviewing.

### General:
- [x] There are no unexpected or unapproved regression image changes. 
- [x] Functionality of interactive elements meet the acceptance criteria.
- [x] The product is visually and functionally the same across the different browsers.

### Accessibility:
- [x] AxeDev Tools: there are no new or outstanding accessibility issues introduced in this PR.
- [x] Lighthouse: scores have not noticeably decreased during this PR.
- [x] Wave: there are no new errors or contrast errors introduced in this PR.

## Design Reviewer PR Checklist
Items the design team is responsible for reviewing.  

### General:
- [ ] New or updated features introduced in this PR are developed mobile-first.
- [ ] Breakpoint changes and regression images match those breakpoints.
- [ ] This PR has been tested in all supported browsers at all breakpoints.

## Developer Reviewer PR Checklist
Items the development team is responsible for reviewing.

### General:
- [ ] New code passes code quality standards set by industry standards.
- [ ] The expected Storybook stories have been added or updated for the new or updated feature.
- [ ] The expected unit tests have been added or updated for the new or updated feature.

### Accessibility:
- [ ] VoiceOver: Described content matches with what was expected.
- [ ] Keyboard navigation: new or updated features and content are navigable via the keyboard.

### CODE REVIEW

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]
The following was figured out based on a call, but adding here for tracing... part of the reason things are not working is because the modal is half tracking focus elements with its `getFocusableElements` method, which the focus-trap already does. The issue is that updateBody and updateButtons are only calling getFocusableElements, leaving the focus-traps' state of focusable elements stale. So when the focustrap keypress fires, it is looking at a list of elements that are not in the modal to figure out what can tab to. So updateBody and updateButtons needs to tell the focus-trap to refresh its lists.

1. Update the focus-trap constructor to take in list of focusable elements defaulting to the current list if one is not provided. The modal should pass in its list.
2. the logic and class variables around getFocusableElements in the modal.component.ts should be removed because it is a duplication of the focus-trap bookkeeping.
3. the focus-trap class should get a method for refreshTrap that calls the this.findFocusableElements(context); . (findFocusableElements(content) sets up the focus-trap's list of focusable elements.
4. Update body and footer methods of modal.component.ts should call refreshTrap after replacing the components and then focus on the "right thing". For now we can assume we should focus the first element. (but in the future we may find update buttons makes more sense to focus on buttons, who knows.

**Review by andyvanavery31 — APPROVED** [review]

File: packages/ncids-js/src/utils/focus-trap.ts [hunk 1]
```diff
@@ -22,11 +20,23 @@ export class FocusTrap {
 	 *
 	 * @param {HTMLElement} element Component being created.
 	 */
-	public constructor(element: HTMLElement) {
+	public constructor(element: HTMLElement, options?: string) {
```
Comment (bryanpizzillo) [inline packages/ncids-js/src/utils/focus-trap.ts:23]: this should not be like that. You should never have something called "options" that is just a string, and a specific option at that.

We should track this as a backlog item to be fixed after this release. (Also, this should be using destructuring with a default...)

e.g.,
```
public constructor(element: HTMLElement, {
  focusableElementSelector = 'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
})
```

**Review by bryanpizzillo — APPROVED** [review]
Platform team says tabbing is all good. I added a comment about the options to the focus-trap, but we will backlog.
